const loremArray = [
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt corrupti praesentium itaque sequi nemo amet cumque expedita eligendi optio recusandae? Quasi error illo veniam blanditiis sunt velit officia doloribus hic facilis consequuntur. Incidunt quod deserunt itaque ullam quia voluptate modi. Doloremque autem earum nam at a id cumque velit animi, distinctio aspernatur hic mollitia enim? Pariatur cupiditate, aliquid dolorum suscipit voluptatibus perferendis quae doloremque delectus illum id quisquam earum est debitis reiciendis temporibus officia doloribus reprehenderit voluptas porro eligendi facilis eius? Excepturi cupiditate modi ducimus nobis labore esse aliquid omnis qui id, nostrum delectus deserunt dolor doloremque nam perspiciatis dolores?",
    "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quae excepturi iste ab cupiditate doloribus quam dicta odio, veritatis dignissimos minus quia autem perferendis eaque perspiciatis voluptatibus nemo et earum vero odit a aperiam assumenda temporibus. Natus consequuntur quaerat recusandae suscipit quasi ipsum officia ullam, similique eligendi odio illo reiciendis labore?",
    "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem in quas iste blanditiis iure illum veritatis aut dolor ea corporis delectus veniam aspernatur, autem sit quaerat? A pariatur sit ipsam reiciendis recusandae, laborum ab. At iusto illo rerum adipisci repudiandae.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum iure temporibus earum dolor ea sunt quisquam eveniet rem cum illo fugiat minus, ad quos qui in mollitia libero saepe doloribus voluptatibus commodi ipsum deleniti esse! Consequatur iste illum iure mollitia amet perferendis, sequi doloremque dolore!",
    "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis, perferendis eveniet. Nemo illum totam quia nisi in ad iste, maiores nostrum rem mollitia iure, soluta vitae quaerat debitis laboriosam dicta ab voluptatem provident consequuntur odit sapiente. Cumque, cum vitae.",
    "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias nisi voluptatum beatae exercitationem consequatur maiores ratione, repellat molestiae accusantium voluptatem tempora quaerat eveniet placeat? Quos, voluptatibus quae! Totam culpa distinctio natus voluptate voluptas in ipsam magni, non reiciendis voluptatibus excepturi expedita amet earum corporis magnam, nemo dolorum repellat facilis odio iste quisquam voluptates? Tenetur harum rem suscipit ex necessitatibus, praesentium, labore vitae reprehenderit dignissimos quaerat soluta numquam id natus voluptatibus culpa voluptate, aliquam debitis. Iusto, dolore cum ex ipsa necessitatibus fuga, eaque itaque molestias quos ea alias temporibus cupiditate voluptas vero ut facilis impedit. Consequuntur rerum voluptates debitis nisi amet.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem dolor placeat nam harum libero, voluptates odit dignissimos quia ullam necessitatibus illo veniam mollitia, sit eum. Eum laboriosam provident, facilis voluptates architecto sit deleniti amet id quia illo placeat itaque modi accusamus officiis similique possimus dolorem nihil magnam optio doloremque totam? Tenetur blanditiis consequuntur corrupti iure voluptate, eligendi in? Earum aperiam nam delectus voluptates nulla quibusdam sunt harum perferendis! Fuga alias atque ab doloribus commodi. Rerum ipsa quas omnis, reprehenderit maxime repellendus ex dolores cumque ipsum sit. Vero beatae nulla deserunt accusantium, explicabo ipsum ut eveniet quo nam minima, vitae natus.",
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis pariatur assumenda iusto natus soluta laudantium debitis eum earum temporibus, enim eos a minima laborum quos voluptates repellat, quo recusandae eveniet ipsa mollitia harum modi cumque cupiditate reprehenderit. Id rem exercitationem, fugiat, eveniet ut perspiciatis autem at obcaecati repellat veritatis delectus iste molestias suscipit repellendus maiores voluptatem consequatur nostrum quidem numquam iure aut, vitae totam facilis. Impedit modi illum ad corrupti quo dignissimos consequatur ut unde repellat et quas itaque blanditiis asperiores natus error recusandae, reiciendis est qui dolor nam tempore repudiandae aperiam eius! Perferendis dolore modi error rem, hic cum?",
    "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat saepe eligendi dolores tempora labore ad veritatis consequatur nobis facere cum voluptatum numquam, quibusdam eaque ut aliquam id magnam, illum inventore ipsam at. Praesentium ad vero quibusdam veniam odit distinctio id commodi assumenda asperiores natus possimus tempora minus molestiae perspiciatis sequi totam accusamus sunt cumque mollitia excepturi, laboriosam quis! Doloremque dolores enim quidem aliquid? Repellendus corporis amet quo tenetur officiis labore, repellat aliquam ratione illum fugit molestiae possimus? Numquam quo fugiat quos rerum voluptatem dolor, corporis explicabo voluptatibus molestiae tempora omnis velit repellat quae ratione minus laborum sequi fugit a assumenda.",
    "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quidem et officiis dolor, harum dolorem excepturi voluptas, accusamus repellat deserunt commodi quasi obcaecati veniam cum, fugit earum natus? Itaque tempora adipisci optio, eaque obcaecati laboriosam vero molestias, eius reprehenderit eligendi modi autem ut odit aliquid qui recusandae amet at delectus tempore, quas in numquam minima laudantium soluta. Nobis omnis ullam commodi harum quam porro vitae! Odio est ipsam aut nisi fugiat molestiae, architecto neque quo nemo cum mollitia veritatis libero vel id delectus. Itaque temporibus dolores molestiae voluptate blanditiis perspiciatis enim perferendis! Officiis, rem ut. Dolores cum recusandae perspiciatis a libero!",
  ];

  export default loremArray;